export type Lang = "en" | "ta" | "hi";

export const langMeta: Record<Lang, { label: string; flag: string; locale: string; speech: string }> = {
  en: { label: "EN", flag: "🇬🇧", locale: "en", speech: "en-IN" },
  ta: { label: "தமிழ்", flag: "🇮🇳", locale: "ta", speech: "ta-IN" },
  hi: { label: "हिन्दी", flag: "🇮🇳", locale: "hi", speech: "hi-IN" },
};

export const t = {
  en: {
    nav: {
      home: "Home",
      features: "Features",
      crops: "Crops",
      predict: "Predict",
      assistant: "AI Assistant",
      contact: "Contact",
    },
    cta: "Request Demo",
    hero: {
      kicker: "Smart farming · powered by AI",
      title1: "Precision yield forecasting for the",
      title2: "modern grower",
      body: "Satellite imagery, soil sensors and micro-climate AI — all in your palm. Predict harvests, prevent losses, and grow more with less.",
      primary: "Begin analysis",
      secondary: "Talk to the AI assistant",
      chip1: "PLOT #A-142 · RICE · 320 ACRES",
      chip2: "FORECAST: 218 BU/AC · +12%",
      side1Label: "Live Paddy Price",
      side1Sub: "+2.4% vs last cycle",
      side2Label: "Region Advisory",
      side2Body: "Optimal planting window opens in 6 days.",
      side2Sub: "Tamil Nadu · Zone 5b",
    },
    metrics: {
      heading: "Real impact, on real fields.",
      items: [
        { v: "14.2%", l: "Average Yield Increase", b: "Across 2.4M hectares of monitored cropland." },
        { v: "₹3,200/ac", l: "Input Cost Reduction", b: "Less fertilizer and water waste with hyper-local prescriptions." },
        { v: "94%", l: "Forecast Accuracy", b: "Precision 30 days before the harvest window closes." },
      ],
    },
    features: {
      kicker: "The Platform",
      heading: "Intelligent layers of growth",
      sub: "One engine, three lenses on your field — from orbit to root zone to market.",
      f1t: "Multispectral vegetation index",
      f1b: "Track biomass health in real time. Detect nitrogen deficiencies 72 hours before they're visible.",
      f2t: "Micro-climate risk engine",
      f2b: "Predict frost, hail and drought windows down to the acre using local + regional models.",
      f3t: "Sub-soil analytics",
      f3b: "Root-zone moisture and nutrient modeling across 5m grids using deep-layer core samples.",
      f4t: "Variable-rate scripts",
      f4b: "Export prescription maps directly to John Deere, Case IH and AGCO equipment.",
      f5t: "Market hedging",
      f5b: "Match harvest volume against global futures to price your yield at the right moment.",
    },
    crops: {
      kicker: "Crop library",
      heading: "Tap a crop to see its features & uses",
      sub: "Localized AI models for every major crop grown across India.",
      hint: "Hover / tap a card",
      features: "Features",
      uses: "Uses",
    },
    how: {
      kicker: "How it works",
      heading: "From orbit to operator in three moves.",
      steps: [
        { t: "Onboard your fields", d: "Draw boundaries or import shapefiles. We backfill three years of imagery in minutes." },
        { t: "Model runs continuously", d: "Daily satellite passes, on-site sensors and weather feeds power a per-plot digital twin." },
        { t: "Act on prescriptions", d: "Get rate maps, alerts and yield forecasts pushed directly to your equipment." },
      ],
    },
    testimonial: {
      quote: "Seeing a yield deficit three weeks in advance let us adjust our nitrogen application and save our entire paddy crop.",
      name: "Erik Sorenson",
      role: "Head of Operations · Heartland Plains Ag",
    },
    cta2: {
      heading: "Ready to optimize your harvest?",
      body: "Join 4,500+ farmers and agribusinesses using Agri on Hands.",
      primary: "Schedule yield assessment",
      secondary: "Speak with an agronomist",
    },
    predict: {
      kicker: "AI Yield Prediction",
      heading: "Forecast your harvest in seconds",
      sub: "Enter your crop, location, soil profile and forecast window. Our model estimates yield, confidence and a smart advisory.",
      crop: "Crop type",
      location: "Location / District",
      locationPh: "e.g. Salem, Tamil Nadu",
      area: "Field area (acres)",
      soilType: "Soil type",
      soilN: "Nitrogen (kg/ha)",
      soilP: "Phosphorus (kg/ha)",
      soilK: "Potassium (kg/ha)",
      soilPH: "Soil pH",
      rainfall: "Expected rainfall (mm)",
      start: "Forecast start",
      end: "Forecast end",
      submit: "Predict yield",
      reset: "Reset",
      result: "Predicted yield",
      perAcre: "per acre",
      total: "Total harvest",
      confidence: "Model confidence",
      advisory: "Advisory",
      soils: ["Loamy", "Clay", "Sandy", "Black cotton", "Red", "Alluvial"],
      askAi: "Ask the AI about this result",
    },
    assistant: {
      kicker: "Voice AI Assistant",
      heading: "Speak. Ask. Grow.",
      sub: "Talk naturally in Tamil, English or Hindi. The assistant listens, understands and answers in real time.",
      placeholder: "Ask about crops, soil, pests, prices…",
      send: "Send",
      listening: "Listening…",
      processing: "Processing…",
      speaking: "Speaking…",
      idle: "Tap the mic and speak",
      mic: "Start voice input",
      stopMic: "Stop listening",
      speakToggle: "Read answers aloud",
      clear: "New conversation",
      you: "You",
      ai: "Agri AI",
      unsupported: "Voice input isn't supported in this browser. Please type your question.",
      error: "Something went wrong. Please try again.",
      suggestions: [
        "How do I increase paddy yield in clay soil?",
        "Best fertilizer schedule for sugarcane?",
        "How to control leaf curl in tomato?",
        "When should I sow cotton in Salem?",
      ],
    },
    contact: {
      kicker: "Contact",
      heading: "Talk to our agronomy team",
      sub: "We're based in Salem, Tamil Nadu and reply within one working day.",
      phone: "Phone",
      email: "Email",
      location: "Location",
      call: "Call now",
      write: "Write to us",
    },
    footer: { rights: "© 2026 Agri on Hands. All rights reserved." },
  },

  ta: {
    nav: {
      home: "முகப்பு",
      features: "வசதிகள்",
      crops: "பயிர்கள்",
      predict: "முன்கணிப்பு",
      assistant: "AI உதவியாளர்",
      contact: "தொடர்பு",
    },
    cta: "டெமோ கேளுங்கள்",
    hero: {
      kicker: "AI மூலம் இயங்கும் புத்திசாலி விவசாயம்",
      title1: "நவீன விவசாயிக்கான",
      title2: "துல்லிய விளைச்சல் முன்கணிப்பு",
      body: "செயற்கைக்கோள் படங்கள், மண் சென்சார்கள் மற்றும் நுண் காலநிலை AI — அனைத்தும் உங்கள் கையில். விளைச்சலை முன்கணிக்கவும், இழப்புகளைத் தடுக்கவும், குறைந்த வளங்களில் அதிகம் விளைவிக்கவும்.",
      primary: "பகுப்பாய்வைத் தொடங்கு",
      secondary: "AI உதவியாளருடன் பேசு",
      chip1: "நிலம் #A-142 · நெல் · 320 ஏக்கர்",
      chip2: "முன்கணிப்பு: 218 மூடை/ஏக்கர் · +12%",
      side1Label: "நெல் விலை (நேரலை)",
      side1Sub: "கடந்த சுழற்சியை விட +2.4%",
      side2Label: "பிராந்திய ஆலோசனை",
      side2Body: "சிறந்த நடவு காலம் 6 நாட்களில் தொடங்கும்.",
      side2Sub: "தமிழ்நாடு · மண்டலம் 5b",
    },
    metrics: {
      heading: "உண்மையான வயல்களில், உண்மையான தாக்கம்.",
      items: [
        { v: "14.2%", l: "சராசரி விளைச்சல் அதிகரிப்பு", b: "2.4M ஹெக்டேர் நிலங்களில் கண்காணிக்கப்பட்டது." },
        { v: "₹3,200/ஏக்", l: "உள்ளீட்டு செலவு குறைப்பு", b: "மிக-உள்ளூர் பரிந்துரைகளால் உரம் மற்றும் நீர் விரயம் குறைகிறது." },
        { v: "94%", l: "முன்கணிப்பு துல்லியம்", b: "அறுவடைக்கு 30 நாட்கள் முன் துல்லியம்." },
      ],
    },
    features: {
      kicker: "தளம்",
      heading: "விளைச்சலின் புத்திசாலித்தனமான அடுக்குகள்",
      sub: "ஒரே இயந்திரம், மூன்று கண்ணோட்டங்கள் — வானிலிருந்து வேர் வரை, சந்தை வரை.",
      f1t: "பன்மைநிற தாவர குறியீடு",
      f1b: "உயிரி நிறை ஆரோக்கியத்தை நேரலையில் கண்காணி. கண்களுக்குத் தெரிவதற்கு 72 மணி நேரத்திற்கு முன்னரே நைட்ரஜன் குறைபாட்டைக் கண்டறியும்.",
      f2t: "நுண் காலநிலை ஆபத்து இயந்திரம்",
      f2b: "உள்ளூர் + பிராந்திய மாதிரிகளைப் பயன்படுத்தி பனிப்பாறை, ஆலங்கட்டி, வறட்சி காலங்களை ஏக்கர் வரை கணிக்கும்.",
      f3t: "மண்ணின் கீழ் பகுப்பாய்வு",
      f3b: "5மீ கட்டங்களில் வேர்-மண்டல ஈரப்பதம் மற்றும் ஊட்டச்சத்து மாதிரியாக்கம்.",
      f4t: "மாறுபட்ட விகித ஸ்கிரிப்ட்கள்",
      f4b: "பரிந்துரை வரைபடங்களை நேரடியாக John Deere, Case IH, AGCO கருவிகளுக்கு ஏற்றுமதி செய்யவும்.",
      f5t: "சந்தை பாதுகாப்பு",
      f5b: "உலகச் சந்தை விலைகளுடன் விளைச்சலைப் பொருத்தி சரியான நேரத்தில் விற்பனை.",
    },
    crops: {
      kicker: "பயிர் நூலகம்",
      heading: "ஒரு பயிரைத் தொட்டால் அதன் வசதிகள் & பயன்கள் தெரியும்",
      sub: "இந்தியாவில் பயிரிடப்படும் ஒவ்வொரு முக்கிய பயிருக்கும் உள்ளூர்மயமாக்கப்பட்ட AI மாதிரிகள்.",
      hint: "ஒரு அட்டையைத் தொடவும்",
      features: "வசதிகள்",
      uses: "பயன்கள்",
    },
    how: {
      kicker: "எப்படி இயங்குகிறது",
      heading: "வானிலிருந்து விவசாயி வரை மூன்று படிகளில்.",
      steps: [
        { t: "உங்கள் வயல்களை பதிவு செய்யுங்கள்", d: "எல்லைகளை வரையவும் அல்லது shapefiles இறக்குமதி செய்யவும். 3 ஆண்டுகள் படங்கள் நிமிடங்களில் சேரும்." },
        { t: "மாதிரி தொடர்ந்து இயங்குகிறது", d: "தினசரி செயற்கைக்கோள், சென்சார்கள், வானிலை உள்ளீடு — ஒவ்வொரு நிலத்திற்கும் டிஜிட்டல் இரட்டையர்." },
        { t: "பரிந்துரைகளின்படி செயல்படு", d: "விகித வரைபடங்கள், எச்சரிக்கைகள், விளைச்சல் முன்கணிப்புகள் — நேரடியாக உங்கள் கருவிகளுக்கு." },
      ],
    },
    testimonial: {
      quote: "விளைச்சல் குறைப்பை மூன்று வாரங்கள் முன்பே பார்த்ததால், நாங்கள் நைட்ரஜனை சரிசெய்து முழு நெல் விளைச்சலையும் காப்பாற்றினோம்.",
      name: "ஏரிக் சொரென்சன்",
      role: "செயல்பாட்டு தலைவர் · ஹார்ட்லேண்ட் பிளைன்ஸ் ஆக்",
    },
    cta2: {
      heading: "உங்கள் அறுவடையை மேம்படுத்த தயாரா?",
      body: "4,500+ விவசாயிகள் மற்றும் விவசாய நிறுவனங்கள் Agri on Hands-ஐ பயன்படுத்துகின்றனர்.",
      primary: "விளைச்சல் மதிப்பீடு பதிவு",
      secondary: "விவசாய நிபுணருடன் பேசு",
    },
    predict: {
      kicker: "AI விளைச்சல் முன்கணிப்பு",
      heading: "சில நொடிகளில் உங்கள் அறுவடையை கணிக்கவும்",
      sub: "பயிர், இடம், மண் விவரம் மற்றும் முன்கணிப்பு காலத்தை உள்ளிடுங்கள். எங்கள் மாதிரி விளைச்சல், நம்பகத்தன்மை மற்றும் ஆலோசனையைக் காட்டும்.",
      crop: "பயிர் வகை",
      location: "இடம் / மாவட்டம்",
      locationPh: "எ.கா. சேலம், தமிழ்நாடு",
      area: "நில பரப்பு (ஏக்கர்)",
      soilType: "மண் வகை",
      soilN: "நைட்ரஜன் (kg/ha)",
      soilP: "பாஸ்பரஸ் (kg/ha)",
      soilK: "பொட்டாசியம் (kg/ha)",
      soilPH: "மண் pH",
      rainfall: "எதிர்பார்க்கும் மழை (மிமீ)",
      start: "முன்கணிப்பு தொடக்கம்",
      end: "முன்கணிப்பு முடிவு",
      submit: "விளைச்சலைக் கணி",
      reset: "மீட்டமை",
      result: "கணிக்கப்பட்ட விளைச்சல்",
      perAcre: "ஏக்கருக்கு",
      total: "மொத்த அறுவடை",
      confidence: "மாதிரி நம்பகத்தன்மை",
      advisory: "ஆலோசனை",
      soils: ["களிமண்", "கடுங்களி", "மணல்", "கருஞ்சி", "சிவப்பு", "வண்டல்"],
      askAi: "இந்த முடிவு பற்றி AI-யிடம் கேளுங்கள்",
    },
    assistant: {
      kicker: "குரல் AI உதவியாளர்",
      heading: "பேசுங்கள். கேளுங்கள். வளருங்கள்.",
      sub: "தமிழ், ஆங்கிலம் அல்லது இந்தியில் இயல்பாக பேசுங்கள். உதவியாளர் கேட்டு, புரிந்து, உடனே பதிலளிக்கும்.",
      placeholder: "பயிர், மண், பூச்சி, விலை பற்றி கேளுங்கள்…",
      send: "அனுப்பு",
      listening: "கேட்கிறது…",
      processing: "செயலாக்கம்…",
      speaking: "பேசுகிறது…",
      idle: "மைக்கை தொட்டு பேசுங்கள்",
      mic: "குரல் உள்ளீட்டைத் தொடங்கு",
      stopMic: "கேட்பதை நிறுத்து",
      speakToggle: "பதில்களை சத்தமாக படி",
      clear: "புதிய உரையாடல்",
      you: "நீங்கள்",
      ai: "அக்ரி AI",
      unsupported: "இந்த உலாவியில் குரல் உள்ளீடு ஆதரிக்கப்படவில்லை. தயவுசெய்து தட்டச்சு செய்யுங்கள்.",
      error: "ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.",
      suggestions: [
        "களிமண்ணில் நெல் விளைச்சலை எப்படி அதிகரிப்பது?",
        "கரும்புக்கு சிறந்த உர அட்டவணை என்ன?",
        "தக்காளியில் இலை சுருட்டை எப்படி கட்டுப்படுத்துவது?",
        "சேலத்தில் பருத்தி எப்போது விதைக்க வேண்டும்?",
      ],
    },
    contact: {
      kicker: "தொடர்பு",
      heading: "எங்கள் விவசாய குழுவை தொடர்பு கொள்ளுங்கள்",
      sub: "நாங்கள் சேலம், தமிழ்நாட்டில் உள்ளோம். ஒரு வேலை நாளில் பதிலளிக்கிறோம்.",
      phone: "தொலைபேசி",
      email: "மின்னஞ்சல்",
      location: "இடம்",
      call: "இப்போது அழை",
      write: "எங்களுக்கு எழுது",
    },
    footer: { rights: "© 2026 Agri on Hands. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை." },
  },

  hi: {
    nav: {
      home: "होम",
      features: "विशेषताएँ",
      crops: "फसलें",
      predict: "पूर्वानुमान",
      assistant: "AI सहायक",
      contact: "संपर्क",
    },
    cta: "डेमो देखें",
    hero: {
      kicker: "AI से संचालित स्मार्ट खेती",
      title1: "आधुनिक किसान के लिए",
      title2: "सटीक उपज पूर्वानुमान",
      body: "सैटेलाइट इमेजरी, मृदा सेंसर और सूक्ष्म-जलवायु AI — सब आपकी हथेली में। उपज का अनुमान लगाएँ, नुकसान रोकें और कम में अधिक उगाएँ।",
      primary: "विश्लेषण शुरू करें",
      secondary: "AI सहायक से बात करें",
      chip1: "प्लॉट #A-142 · धान · 320 एकड़",
      chip2: "पूर्वानुमान: 218 बु/एकड़ · +12%",
      side1Label: "धान का लाइव भाव",
      side1Sub: "पिछले चक्र से +2.4%",
      side2Label: "क्षेत्रीय सलाह",
      side2Body: "बुवाई की सर्वोत्तम अवधि 6 दिनों में शुरू होगी।",
      side2Sub: "तमिलनाडु · ज़ोन 5b",
    },
    metrics: {
      heading: "असली खेतों पर, असली असर।",
      items: [
        { v: "14.2%", l: "औसत उपज वृद्धि", b: "24 लाख हेक्टेयर निगरानी वाली कृषि भूमि पर।" },
        { v: "₹3,200/एकड़", l: "लागत में कमी", b: "अति-स्थानीय सिफारिशों से उर्वरक और पानी की बचत।" },
        { v: "94%", l: "पूर्वानुमान सटीकता", b: "कटाई से 30 दिन पहले सटीक अनुमान।" },
      ],
    },
    features: {
      kicker: "प्लेटफ़ॉर्म",
      heading: "विकास की बुद्धिमान परतें",
      sub: "एक इंजन, तीन दृष्टिकोण — कक्षा से जड़ तक और बाज़ार तक।",
      f1t: "मल्टीस्पेक्ट्रल वनस्पति सूचकांक",
      f1b: "बायोमास स्वास्थ्य की वास्तविक समय निगरानी। नाइट्रोजन की कमी दिखने से 72 घंटे पहले पहचान।",
      f2t: "सूक्ष्म-जलवायु जोखिम इंजन",
      f2b: "स्थानीय + क्षेत्रीय मॉडल से पाला, ओलावृष्टि और सूखे की अवधि का एकड़-स्तरीय अनुमान।",
      f3t: "उप-मृदा विश्लेषण",
      f3b: "5 मीटर ग्रिड पर जड़-क्षेत्र की नमी और पोषक तत्वों का मॉडलिंग।",
      f4t: "वैरिएबल-रेट स्क्रिप्ट",
      f4b: "प्रिस्क्रिप्शन मैप सीधे John Deere, Case IH और AGCO उपकरणों में भेजें।",
      f5t: "बाज़ार हेजिंग",
      f5b: "वैश्विक वायदा भाव से उपज का मिलान कर सही समय पर बेचें।",
    },
    crops: {
      kicker: "फसल पुस्तकालय",
      heading: "किसी फसल को छूकर उसकी विशेषताएँ और उपयोग देखें",
      sub: "भारत की हर प्रमुख फसल के लिए स्थानीयकृत AI मॉडल।",
      hint: "कार्ड पर टैप करें",
      features: "विशेषताएँ",
      uses: "उपयोग",
    },
    how: {
      kicker: "यह कैसे काम करता है",
      heading: "कक्षा से किसान तक, तीन चरणों में।",
      steps: [
        { t: "अपने खेत जोड़ें", d: "सीमाएँ बनाएँ या shapefiles आयात करें। तीन साल की इमेजरी मिनटों में जुड़ जाती है।" },
        { t: "मॉडल लगातार चलता है", d: "दैनिक सैटेलाइट, सेंसर और मौसम डेटा से हर प्लॉट का डिजिटल ट्विन।" },
        { t: "सिफारिशों पर काम करें", d: "रेट मैप, अलर्ट और उपज पूर्वानुमान सीधे आपके उपकरणों पर।" },
      ],
    },
    testimonial: {
      quote: "तीन सप्ताह पहले उपज में कमी दिखने से हमने नाइट्रोजन समायोजित किया और पूरी धान की फसल बचा ली।",
      name: "एरिक सोरेनसन",
      role: "संचालन प्रमुख · हार्टलैंड प्लेन्स ऐग",
    },
    cta2: {
      heading: "अपनी फसल को बेहतर बनाने के लिए तैयार?",
      body: "4,500+ किसान और कृषि व्यवसाय Agri on Hands का उपयोग कर रहे हैं।",
      primary: "उपज मूल्यांकन बुक करें",
      secondary: "कृषि विशेषज्ञ से बात करें",
    },
    predict: {
      kicker: "AI उपज पूर्वानुमान",
      heading: "सेकंडों में अपनी फसल का अनुमान लगाएँ",
      sub: "फसल, स्थान, मृदा विवरण और अवधि दर्ज करें। हमारा मॉडल उपज, विश्वास स्तर और सलाह देगा।",
      crop: "फसल का प्रकार",
      location: "स्थान / ज़िला",
      locationPh: "जैसे सेलम, तमिलनाडु",
      area: "खेत का क्षेत्रफल (एकड़)",
      soilType: "मिट्टी का प्रकार",
      soilN: "नाइट्रोजन (kg/ha)",
      soilP: "फॉस्फोरस (kg/ha)",
      soilK: "पोटैशियम (kg/ha)",
      soilPH: "मिट्टी pH",
      rainfall: "अपेक्षित वर्षा (मिमी)",
      start: "पूर्वानुमान प्रारंभ",
      end: "पूर्वानुमान समाप्ति",
      submit: "उपज का अनुमान लगाएँ",
      reset: "रीसेट",
      result: "अनुमानित उपज",
      perAcre: "प्रति एकड़",
      total: "कुल उपज",
      confidence: "मॉडल विश्वास",
      advisory: "सलाह",
      soils: ["दोमट", "चिकनी", "बलुई", "काली कपास", "लाल", "जलोढ़"],
      askAi: "इस परिणाम पर AI से पूछें",
    },
    assistant: {
      kicker: "वॉइस AI सहायक",
      heading: "बोलिए। पूछिए। बढ़िए।",
      sub: "तमिल, अंग्रेज़ी या हिंदी में सहजता से बोलें। सहायक सुनता है, समझता है और तुरंत जवाब देता है।",
      placeholder: "फसल, मिट्टी, कीट, भाव के बारे में पूछें…",
      send: "भेजें",
      listening: "सुन रहा है…",
      processing: "प्रोसेस हो रहा है…",
      speaking: "बोल रहा है…",
      idle: "माइक दबाकर बोलें",
      mic: "वॉइस इनपुट शुरू करें",
      stopMic: "सुनना बंद करें",
      speakToggle: "उत्तर सुनाएँ",
      clear: "नई बातचीत",
      you: "आप",
      ai: "एग्री AI",
      unsupported: "इस ब्राउज़र में वॉइस इनपुट समर्थित नहीं है। कृपया टाइप करें।",
      error: "कुछ गड़बड़ हुई। कृपया पुनः प्रयास करें।",
      suggestions: [
        "चिकनी मिट्टी में धान की उपज कैसे बढ़ाएँ?",
        "गन्ने के लिए सर्वोत्तम उर्वरक शेड्यूल?",
        "टमाटर में पत्ती मरोड़ कैसे रोकें?",
        "सेलम में कपास कब बोएँ?",
      ],
    },
    contact: {
      kicker: "संपर्क",
      heading: "हमारी कृषि टीम से बात करें",
      sub: "हम सेलम, तमिलनाडु में हैं और एक कार्यदिवस में उत्तर देते हैं।",
      phone: "फ़ोन",
      email: "ईमेल",
      location: "स्थान",
      call: "अभी कॉल करें",
      write: "हमें लिखें",
    },
    footer: { rights: "© 2026 Agri on Hands. सर्वाधिकार सुरक्षित।" },
  },
} satisfies Record<Lang, unknown>;

export type Copy = (typeof t)["en"];
